version: '2'
services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    networks:
      - arm-mreza
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wt22

  nodejs-app:
    build: .
    image: fsahat1/dockerzadaca:nodejs-app
    container_name: nodejs-app
    ports:
      - "8080:8080"
    networks:
      - arm-mreza
    depends_on:
      - mysql-db
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

networks:
  arm-mreza:
    name: arm-mreza
    driver: bridge